version: '3.8'

services:
  app:
    build: .
    image: tonycarvalho1994/butcher:v1
    command: uvicorn app.infra.http.fastapi:app --host ${APP_HOST}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}